### ISSUE TITLE
For example

### ISSUE THREAD

**Issue by aquastripe** [ricky-696/ROADpp_challenge_ICCV2023#1]
https://github.com/ricky-696/ROADpp_challenge_ICCV2023/blob/02cd6c184613b22847d4b6328d5c298f5cd7deb1/detect.py#L11-L14

**Comment by ricky-696** [comment]
> https://github.com/ricky-696/ROADpp_challenge_ICCV2023/blob/02cd6c184613b22847d4b6328d5c298f5cd7deb1/detect.py#L11-L14

got it
